console.log('Name is : Beqa')
console.log('Surname is : Dididze')
console.log('Age is : 15')
console.warn('Email : beqadididze2@gmail.com')
console.warn('Password : safhuhaiuh')
console.log('Phone : 599475225')